### ISSUE TITLE
Perplexica not working on fresh installation

### ISSUE THREAD

**Issue by mystogan99** [ItzCrazyKns/Perplexica#180]
**Describe the bug**
After installing and running Perplexica, the application does not load and keeps loading indefinitely. I have followed the installation instructions to the dot. There are no errors in the logs.

**To Reproduce**

1. Follow the installation instructions as provided in the documentation.
2. Run the application.

**Expected behavior**
The application should load and display the main interface.

**Screenshots**
<img width="1792" alt="Screenshot 2024-06-09 at 11 45 44 PM" src="https://github.com/ItzCrazyKns/Perplexica/assets/43119272/e19ba28d-6427-49d2-963f-ae681bbef3e3">

**Comment by mystogan99** [comment]
I have added the size as `size? : number` type for prop given to `ThemeSwither` component. At path `ui/components/theme/Switcher.tsx`. This is the only change I did. This should not cause any trouble.

**Comment by LalithShiyam** [comment]
Many thanks for bringing this up. I have the same issue as well.

**Comment by bertusviljoen** [comment]
Had the same issue

**Comment by Amirjab21** [comment]
Are you guys running this on Docker?

I couldn't get it working without Docker as you have to run searxng at the same time.

If you pull and run the public docker image, it runs all components for you and it should work. (You still have to toggle the model selection on the UI to choose your model)

**Comment by LalithShiyam** [comment]
Hi @Amirjab21, thanks for chiming in. I do run via docker (ubuntu OS), everything builds successfully (frontend, backend, searxng). When I go to the page using my privateIP and port. It just keeps 'loading'. I can't choose much as everything is just loading as shown in the screenshot.

**Comment by Amirjab21** [comment]
> Hi @Amirjab21, thanks for chiming in. I do run via docker (ubuntu OS), everything builds successfully (frontend, backend, searxng). When I go to the page using my privateIP and port. It just keeps 'loading'. I can't choose much as everything is just loading as shown in the screenshot.
> 
> This project looks so cool, that I can't wait to get it up and running 😄

Did you remove the size attribute from ThemeSwitcher component on the UI? I had to do this as it was causing a typescript error

**Comment by LalithShiyam** [comment]
I have ollama installed and I have llama3 and llama3:70b setup.

This is my `config.toml`

```TOML
[GENERAL]
PORT = 3001 # Port to run the server on
SIMILARITY_MEASURE = "cosine" # "cosine" or "dot"

[API_KEYS]
OPENAI = "" # OpenAI API key - sk-1234567890abcdef1234567890abcdef
GROQ = "" # Groq API key - gsk_1234567890abcdef1234567890abcdef

[API_ENDPOINTS]
SEARXNG = "http://localhost:32768" # SearxNG API URL
OLLAMA = "http://host.docker.internal:11434"
```

But I don't think I made a copy of the .env file into the UI folder though...

Also should the SearxNG API port be 8080?

**Comment by LalithShiyam** [comment]
Hi everyone,

I managed to resolve the issue, and I'd like to share the steps I followed. It turns out I missed some details in the documentation, particularly in the `Networking.md` file. Below are the steps I took to get everything working smoothly.

### Steps to Resolve the Issue

1. **Verify Ollama is Running**
   Ensure that the Ollama service is up and running if you are using it.

2. **Bring Down Existing Docker Services**

   ```bash
   sudo docker compose down
   ```

3. **Update `docker-compose.yaml`**
   Modify your `docker-compose.yaml` file to use the correct IP address of the server hosting Perplexica. Update the relevant sections as shown below:
   
   ```yaml
     perplexica-frontend:
       build:
         context: .
         dockerfile: app.dockerfile
       args:
         - NEXT_PUBLIC_API_URL=http://xxx.xxx.xxx.xx:3001/api
         - NEXT_PUBLIC_WS_URL=ws://xxx.xxx.xxx.xx:3001 # Replace xxx.xxx.xxx.xx with your server's IP address
       depends_on:
         - perplexica-backend
       ports:
         - 3000:3000
   ```

4. **Update `config.toml`**
   Similarly, update the `config.toml` file to reflect the correct IP addresses for the services. Here’s an example of how the configuration might look:

   ```toml
   [GENERAL]
   PORT = 3001  # Port to run the server on
   SIMILARITY_MEASURE = "cosine"  # Choose between "cosine" or "dot"

   [API_KEYS]
   OPENAI = ""  # Your OpenAI API key
   GROQ = ""  # Your Groq API key

   [API_ENDPOINTS]
   SEARXNG = "http://xxx.xxx.xxx.xx:32768"  # Replace xxx.xxx.xxx.xx with your server's IP address for SearxNG
   OLLAMA = "http://xxx.xxx.xxx.xx:11434"  # Replace xxx.xxx.xxx.xx with your server's IP address for Ollama
   ```

5. **Rebuild and Restart Docker Services**
   After updating the configuration files, rebuild and restart your Docker services:
   ```bash
   sudo docker compose up -d --build
   ```

6. **Access Perplexica**
   Once the services are up, access Perplexica via your web browser at:
   ```url
   http://xxx.xxx.xxx.xx:3000
   ```
   Replace `xxx.xxx.xxx.xx` with your server’s IP address.

Enjoy using Perplexica!

Cheers and hope it helps, 
Lalith

**Comment by N1RM4L13** [comment]
@LalithShiyam after following your mentioned steps , still face issues with loading Ollama

**Comment by LalithShiyam** [comment]
Hi @N1RM4L13 when you say issues in loading ollama - can you be a bit more elaborate?

**Comment by N1RM4L13** [comment]
@LalithShiyam 
As you can see the ollama is active 
![Screenshot 2024-06-11 140249](https://github.com/ItzCrazyKns/Perplexica/assets/121315038/c8723ffc-15a7-452f-a28e-9ba386307eb0)

And when running the docker , i get the following error
![Screenshot 2024-06-11 140921](https://github.com/ItzCrazyKns/Perplexica/assets/121315038/d0842f2b-228e-4472-9092-387e343e9b33)

**Comment by LalithShiyam** [comment]
Strange, I haven't seen this error so far... Just to confirm, can you please check the http:xxx.xxx.xxx.xx:port (on your browser) where ollama is supposed to run. And let me know if you see something like this?

![image](https://github.com/ItzCrazyKns/Perplexica/assets/48599863/29f94766-78eb-433c-a8f2-3cf599eb0bbf)

**Comment by N1RM4L13** [comment]
Not able to see this in browser , but my port 11434 open

**Comment by LalithShiyam** [comment]
I think this might be a reason. But I am not sure. Are you able to run ollama from your terminal (ollama run llama3b) and if you do the same with ollama serve?

**Comment by N1RM4L13** [comment]
> I think this might be a reason. But I am not sure. Are you able to run ollama from your terminal (ollama run llama3b) and if you do the same with ollama serve?

Okay i fixed this by running ollama serve in a terminal and using docker command on another, but now it doesnt show ollama models list present in my server.
Yes im able to run models locally.

**Comment by N1RM4L13** [comment]
> Hi everyone,
> 
> I managed to resolve the issue, and I'd like to share the steps I followed. It turns out I missed some details in the documentation, particularly in the `Networking.md` file. Below are the steps I took to get everything working smoothly.
> 
> ### Steps to Resolve the Issue
> 1. **Verify Ollama is Running**
>    Ensure that the Ollama service is up and running if you are using it.
> 2. **Bring Down Existing Docker Services**
>    ```shell
>    sudo docker compose down
>    ```
> 3. **Update `docker-compose.yaml`**
>    Modify your `docker-compose.yaml` file to use the correct IP address of the server hosting Perplexica. Update the relevant sections as shown below:
>    ```yaml
>      perplexica-frontend:
>        build:
>          context: .
>          dockerfile: app.dockerfile
>        args:
>          - NEXT_PUBLIC_API_URL=http://xxx.xxx.xxx.xx:3001/api
>          - NEXT_PUBLIC_WS_URL=ws://xxx.xxx.xxx.xx:3001 # Replace xxx.xxx.xxx.xx with your server's IP address
>        depends_on:
>          - perplexica-backend
>        ports:
>          - 3000:3000
>    ```
> 4. **Update `config.toml`**
>    Similarly, update the `config.toml` file to reflect the correct IP addresses for the services. Here’s an example of how the configuration might look:
>    ```toml
>    [GENERAL]
>    PORT = 3001  # Port to run the server on
>    SIMILARITY_MEASURE = "cosine"  # Choose between "cosine" or "dot"
>    
>    [API_KEYS]
>    OPENAI = ""  # Your OpenAI API key
>    GROQ = ""  # Your Groq API key
>    
>    [API_ENDPOINTS]
>    SEARXNG = "http://xxx.xxx.xxx.xx:32768"  # Replace xxx.xxx.xxx.xx with your server's IP address for SearxNG
>    OLLAMA = "http://xxx.xxx.xxx.xx:11434"  # Replace xxx.xxx.xxx.xx with your server's IP address for Ollama
>    ```
> 5. **Rebuild and Restart Docker Services**
>    After updating the configuration files, rebuild and restart your Docker services:
>    ```shell
>    sudo docker compose up -d --build
>    ```
> 6. **Access Perplexica**
>    Once the services are up, access Perplexica via your web browser at:
>    ```ini
>    http://xxx.xxx.xxx.xx:3000
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Replace `xxx.xxx.xxx.xx` with your server’s IP address.
> 
> Enjoy using Perplexica!
> 
> Cheers and hope it helps, Lalith

Hello Everyone 
if anyone face this error after following the steps mention by @LalithShiyam 
![Screenshot 2024-06-11 140921](https://github.com/ItzCrazyKns/Perplexica/assets/121315038/f3783680-4c10-43af-a5b4-3b583155c5f5)

1. Run `ollama serve` (Make sure port number is open in inbound rules , default port is 11434)
Check by typing http://x.xxx.xxx.xx:11434 in browser. The browser will show the following.
![Screenshot 2024-06-11 145018](https://github.com/ItzCrazyKns/Perplexica/assets/121315038/9d6aa72d-c0b5-4d94-8f6a-c1e2b39a5baf)

2. Run the command `ollama run (model_name)`

3. Now run `docker compose up --build`

**Comment by LalithShiyam** [comment]
Great @N1RM4L13 so everything is working now right?

**Comment by Just10McGill** [comment]
Thank you guys so much, I was having this problem as well.

**Comment by N1RM4L13** [comment]
> Great @N1RM4L13 so everything is working now right?
Yes , thanks for the fix above 💪🏻

**Comment by LalithShiyam** [comment]
@N1RM4L13 Fantastic - glad it worked out! 🥳

**Comment by menelic** [comment]
Unfortunately I cannot get it to work on ubuntu 22.04, with ollama up and running

![image](https://github.com/ItzCrazyKns/Perplexica/assets/5934115/1fd20c38-5d84-4047-9feb-52d42c4f41e2)

and with all of @LalithShiyam s instructions followed

the perplexica page can be opened, it first shows the perplexica interface, but typing anything in there does not lead to any results. When clicking on say the image search option, the perplexia interface changes to read:

![image](https://github.com/ItzCrazyKns/Perplexica/assets/5934115/ed0b5b24-25a2-4037-a816-3510f4d4f86d)

I have shut down and re-upped docker severally, I have run ollama both inside and oustide the directory, in the same and in another terminal...please assist, I really want to get this running!

**Comment by LalithShiyam** [comment]
Hi @menelic, seems like this could be a new error altogether, because I never got the internal server error. But I might be wrong. And it was ubuntu 22.04 for me as well.

**Comment by Ranganaths** [comment]
Even i get the same error
- JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by braindotai** [comment]
Same issue here, I just don't understand... ollama is running locally on my system. Docker backend simply has to make a request to ollama's URL in the host (local)... 
```
extra_hosts:
    - "host.docker.internal:host-gateway"
```
Above code in docker compose should be good to go **if everything else is implemented correctly**. What's the big deal with this? This should not be that hard to figure it out

**Comment by mystogan99** [comment]
Is it just me or are the results extremely slow for everyone? I am running this on a CPU-only instance. 
Ubuntu 23.10
128 Gigs Ram
20 vCPU

**Comment by creuzerm** [comment]
The additional config on config.toml and docker-compose.yaml fixed my forever-loading-wheel as well on ubuntu24 docker. So I think we have a deficiency in the quick start instructions.

**Comment by jiafu83** [comment]
> Hi everyone,
> 
> I managed to resolve the issue, and I'd like to share the steps I followed. It turns out I missed some details in the documentation, particularly in the `Networking.md` file. Below are the steps I took to get everything working smoothly.
> 
> ### Steps to Resolve the Issue
> 1. **Verify Ollama is Running**
>    Ensure that the Ollama service is up and running if you are using it.
> 2. **Bring Down Existing Docker Services**
>    ```shell
>    sudo docker compose down
>    ```
> 3. **Update `docker-compose.yaml`**
>    Modify your `docker-compose.yaml` file to use the correct IP address of the server hosting Perplexica. Update the relevant sections as shown below:
>    ```yaml
>      perplexica-frontend:
>        build:
>          context: .
>          dockerfile: app.dockerfile
>        args:
>          - NEXT_PUBLIC_API_URL=http://xxx.xxx.xxx.xx:3001/api
>          - NEXT_PUBLIC_WS_URL=ws://xxx.xxx.xxx.xx:3001 # Replace xxx.xxx.xxx.xx with your server's IP address
>        depends_on:
>          - perplexica-backend
>        ports:
>          - 3000:3000
>    ```
> 4. **Update `config.toml`**
>    Similarly, update the `config.toml` file to reflect the correct IP addresses for the services. Here’s an example of how the configuration might look:
>    ```toml
>    [GENERAL]
>    PORT = 3001  # Port to run the server on
>    SIMILARITY_MEASURE = "cosine"  # Choose between "cosine" or "dot"
>    
>    [API_KEYS]
>    OPENAI = ""  # Your OpenAI API key
>    GROQ = ""  # Your Groq API key
>    
>    [API_ENDPOINTS]
>    SEARXNG = "http://xxx.xxx.xxx.xx:32768"  # Replace xxx.xxx.xxx.xx with your server's IP address for SearxNG
>    OLLAMA = "http://xxx.xxx.xxx.xx:11434"  # Replace xxx.xxx.xxx.xx with your server's IP address for Ollama
>    ```
> 5. **Rebuild and Restart Docker Services**
>    After updating the configuration files, rebuild and restart your Docker services:
>    ```shell
>    sudo docker compose up -d --build
>    ```
> 6. **Access Perplexica**
>    Once the services are up, access Perplexica via your web browser at:
>    ```ini
>    http://xxx.xxx.xxx.xx:3000
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Replace `xxx.xxx.xxx.xx` with your server’s IP address.
> 
> Enjoy using Perplexica!
> 
> Cheers and hope it helps, Lalith

Thanks, this really sovles my problem, the key is give the real ip address, instead of 127.0.0.1, for other computers to use it in the lan

**Comment by gerhardmpl** [comment]
The forever-loading-wheel may also mean that your firewall is blocking port 3001/tcp. So check your firewall after you have changed config.toml and docker-compose.yaml (which is indeed necessary).

**Comment by ncecere** [comment]
The thin i forgot to do was run 

`docker compose down --rmi all`

because of

```yaml
  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
    args:
      - NEXT_PUBLIC_API_URL=http://xxx.xxx.xxx.xx:3001/api
      - NEXT_PUBLIC_WS_URL=ws://xxx.xxx.xxx.xx:3001 # Replace xxx.xxx.xxx.xx with your server's IP address
    depends_on:
      - perplexica-backend
    ports:
      - 3000:3000
```

the arguments `NEXT_PUBLIC_API_URL` and `NEXT_PUBLIC_WS_URL` are used when building the frontend container.  I just kept doing a docker compose down and never rebuilt the container images with the new IP information.
