### ISSUE TITLE
WebSocket Error within a short period after receiving a response

### ISSUE THREAD

**Issue by manjaroblack** [ItzCrazyKns/Perplexica#244]
**Describe the bug**
A short time after entering a prompt and receiving a response, maybe 1-2 minutes, the prompt disappears and is replaced with a message “Failed to connect to the server. Please try again later.” and a pop up in the bottom right appears briefly stating there is a WebSocket Connection Error.

**To Reproduce**

1. Enter a prompt and wait for a response
2. After the response finishes, wait a minute or two

**Expected behavior**
The prompt should remain visible no matter the length of time elapses

**Screenshots**
![IMG_0183](https://github.com/ItzCrazyKns/Perplexica/assets/42281273/99731ec1-4b9c-4d70-bc85-2406c72739b1)

**Comment by ItzCrazyKns** [comment]
What are the logs from the backend container?

**Comment by BartWillems** [comment]
I have the same issue, there are no logs for this in the backend container nor in the browser's console.

**Comment by rick-github** [comment]
I see this when the server is behind a proxy.  The proxy disconnects connections that have been idle for a while (60 seconds in my case).  I'm unable to influence the owner of the proxy, so the solution seems to be a ping message from the client to the backend every n seconds.

**Comment by alex14dark** [comment]
The solution is for the client to send a heartbeat every once in a while, for example, 30 seconds.

**Comment by ProjectMoon** [comment]
This is an important thing to fix. It happens a lot, even with my reverse proxy's timeouts set very high. Maybe I haven't configured nginx properly, but I think I have. o_O

This is also how OpenWebUI maintains its connectivity to the backend without issue.

**Comment by ItzCrazyKns** [comment]
I will try to reproduce this.

**Comment by ItzCrazyKns** [comment]
Unfortunately, I cannot reproduce this. Maybe it seems like an issue with your reverse proxy.

**Comment by ProjectMoon** [comment]
I will double check the reverse proxy configuration and also try connecting directly.

**Comment by ProjectMoon** [comment]
I added a 600 second timeout to all places I can think of for the websocket. It doesn't timeout immediately, but it still eventually drops off.

I think the problem here is not necessarily that the web socket closes, but more that when it DOES close, it kills the whole page. Ideally, if ping-pong isn't implemented, it should just keep the page as-is and automatically reopen the web socket when needed.

**Comment by ProjectMoon** [comment]
So, fixing this may not require much more than changing one line. I noticed that error state is set to true when the websocket closes. This causes the entire window to die, and requires the user to refresh. Since the application is already coded to handle the websocket being null, simply setting it back to null forces it to reopen in the event of a close.

in my tests, I notice that the web socket immediately reopens when it closes. Probably something else reopens it. But this is good behavior! Rather than relying on a properly configured reverse proxy, or lack of reverse proxy, the application can handle its own websocket closing.

See here: https://git.agnos.is/projectmoon/perplexica/commit/f8f1b31cb3e7dc7dbb7de19e07061de71c8c3f85

I can open a PR on GitHub if you want.

**Comment by Stumie** [comment]
This is the related pull request, isn't it?
https://github.com/ItzCrazyKns/Perplexica/pull/292

**Comment by ProjectMoon** [comment]
Yes.

**Comment by AxelFooley** [comment]
I have the same issue: https://github.com/ItzCrazyKns/Perplexica/issues/305
i am also running behind a reverse proxy but i also tried accessing the container directly bypassing the proxy and the issue is still happening.
No logs from container nor in browser console.

**Comment by ProjectMoon** [comment]
> I have the same issue: #305 i am also running behind a reverse proxy but i also tried accessing the container directly bypassing the proxy and the issue is still happening. No logs from container nor in browser console.

Have you tried merging my PR into your fork (if you have one) and seeing if it works for you?

I have been testing my changes and for the most part it seems to work. There are perhaps still some edge cases, though, and more people testing it would help a lot.

**Comment by AxelFooley** [comment]
i am not forking, i just cloned your repo on my home server and git pull says i am up to date? do i have to switch to any specific branch to test?

**Comment by ProjectMoon** [comment]
Something like this:

```
git remote add projectmoon https://github.com/ProjectMoon/Perplexica
git fetch projectmoon
git checkout projectmoon/master
```

Or merge it into origin: `git merge projectmoon/master` 

For testing, it's probably best to keep a separate branch.

**Comment by AxelFooley** [comment]
Just tried, recreated all the containers after checking out this new branch and after a couple of minutes the results page is gone

**Comment by ProjectMoon** [comment]
Hmm, I experience the exact opposite lol. Can you share browser console logs?

**Comment by AxelFooley** [comment]
this is why this issue is tricky, i get absolutely nothing not on my browser nor in container logs
![image](https://github.com/user-attachments/assets/dc853279-5897-451b-9c04-d47c16913f75)

**Comment by ProjectMoon** [comment]
Hmm are you absolutely sure you are on my branch? Because you should see some log messages about attempting to reconnect, which I added.

**Comment by AxelFooley** [comment]
i do :) but let me know if i have to provide additional details

`:~/src/Perplexica$ git status
HEAD detached at projectmoon/master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   docker-compose.yaml
	modified:   sample.config.toml
	modified:   searxng/settings.yml

no changes added to commit (use "git add" and/or "git commit -a")`

**Comment by ProjectMoon** [comment]
What command did you enter to restart the docker compose services after switching branches?

**Comment by AxelFooley** [comment]
Docker compose up --build --force-recreate

**Comment by AxelFooley** [comment]
It gives me exactly that page, I have posted the screenshot in the other issue I've opened which is linked above. Black screen with that message in the middle and nothing else.

Is there any change I can make to enable some debugging in the browser console or in the container logs?

**Comment by ProjectMoon** [comment]
Yes that message is the one I meant. It's used in two places. One is on an actual error, and the other is when the web socket closed and set error state. So you might be hitting a different code path than what I changed. I can explain better once I'm in front of a computer.

**Comment by AxelFooley** [comment]
Cheers I appreciate the support.

**Comment by ProjectMoon** [comment]
Ok so there are two ways that the error message shows up:

1. There is a timeout that fires if the websocket does not connect properly. If this timeout is hit, it will show the error state.
2. If the error state is set specifically, it'll also switch to the error message.

Both of these are in ChatWindow.tsx.

The error state being set directly can happen under these conditions:

1. WebSocket `onerror` event.
2. (On my branch) if reconnect attempts fail too many times.
3. Configuration error regarding OpenAI.

The `[DEBUG] open` and close messages happen on the `onopen` and `onclose` event handlers of the web socket. The flow of the code is that these event handlers are set up, and then the connection is opened. You should see at least one reconnect attempt on message when using my branch, which is why it's a bit odd that you don't have them.

Based on what you show me, I am thinking you're hitting the timeout code path:

```javascript
        const timeoutId = setTimeout(() => {
          if (ws.readyState !== 1) {
            toast.error(
              'Failed to connect to the server. Please try again later.',
            );
          }
        }, 10000);
```

But I can't be certain. Maybe try adding a bunch of `console.log`s in `ChatWindow.tsx` to trace what's going on, and deploy again. The function that needs logging is `useSocket` and more specifically the `connectWs` within it.

**Comment by AxelFooley** [comment]
I don't have an explanation, but now it's working, all i did was adding console.log all over the place as you can see from my browser console.
![image](https://github.com/user-attachments/assets/588e6134-fbc7-4dc0-8fa1-f5b7d3d099fb)

At this point i started thinking that even though i am using `docker compose up --build --force-recreate` for some reason it didn't recreate the containers after switching to your branch.

Do you want me to push my changes on a separate branch for review?

**Comment by ProjectMoon** [comment]
If the changes are only console logs, probably not necessary to push them. But yeah it sounds like containers didn't get recreated. It's interesting that the connection closing isn't clean though.

**Comment by ItzCrazyKns** [comment]
Hi, I just pushed a commit that fixes this issue, please reclone the project from Github and rebuild images via

`docker compose up -d --build`

**Comment by Stumie** [comment]
Thank you, @ItzCrazyKns! Though... I deleted the whole repo on my system, rebuilt (with `--build` parameter added) on tag v1.9.0-rc2, additionally deleted my browser cache, but I still get the same issue that manjaroblack posted in his initial post. So, at least for me, the fix does not seem to work.

**Comment by Stumie** [comment]
> Do you mind posting your nginx configuration of all your timeout settings?

Though I'm not the one addressed, I'll share my nginx configuration, since I do have the same issue.

I personally use/host perplexica on Fedora CoreOS via a custom docker-compose.yaml in rootless podman containers.
Nginx is is running in the same setup, as well as ollama, though for nginx I specifically use the [nginx-unprivileged image](https://github.com/nginxinc/docker-nginx-unprivileged). 

This is the nginx configuration, where I changed my domain names to 'my.domain.name' for sharing it here:
```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
upstream perplexica-frontend {
    server perplexica-perplexica-frontend-1:3000;
    keepalive 1;
}
upstream perplexica-backend {
    server perplexica-perplexica-backend-1:3001;
    keepalive 1;
}
upstream perplexica-ollama {
    server perplexica-ollama-1:11434;
    keepalive 1;
}
server {
    listen 8443 ssl;
    listen [::]:8443 ssl;
    server_name my.domain.name;

    ssl_certificate /ssl/selfsigned.crt;
    ssl_certificate_key /ssl/selfsigned.key;

    send_timeout          600s;
    client_body_timeout   600s;
    client_header_timeout 600s;

    proxy_buffering off;
    proxy_cache off;
    proxy_redirect off;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Protocol $scheme;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_connect_timeout 600s;
    proxy_send_timeout    600s;
    proxy_read_timeout    600s;

    add_header 'Access-Control-Allow-Origin' '*';

    location / {
        proxy_pass http://perplexica-frontend;
    }

    location /api {
        proxy_pass http://perplexica-backend/api;
    }

    location /socket {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_pass http://perplexica-backend;
    }

    location /ollama/ {
        proxy_pass http://perplexica-ollama/;
    }
}
```

This is my 'custom' `docker-compose.yaml`, where I added ollama and nginx, added SELinux volume flags, removed some ports, and for sharing it here changed my domain names to 'my.domain.name':
```
services:
  ollama:
    image: docker.io/ollama/ollama:latest
    environment:
      OLLAMA_LLM_LIBRARY: "cpu_avx2"
    volumes:
      - ollama-volume:/root/.ollama:Z
    networks:
      - perplexica-network
    restart: unless-stopped

  searxng:
    image: docker.io/searxng/searxng:latest
    depends_on:
      - ollama
    volumes:
      - ./searxng:/etc/searxng:rw,z
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        - SEARXNG_API_URL=http://perplexica-searxng-1:8080/
    depends_on:
      - ollama
      - searxng
    volumes:
      - backend-dbstore:/home/perplexica/data:Z
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://my.domain.name/api
        - NEXT_PUBLIC_WS_URL=wss://my.domain.name/socket
    depends_on:
      - ollama
      - perplexica-backend
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-reverse-proxy:
    image: quay.io/nginx/nginx-unprivileged:latest
    volumes:
      - /home/perplexica/.nginx/perplexica.conf:/etc/nginx/conf.d/perplexica.conf:ro,Z
      - /home/perplexica/.ssl:/ssl:ro,Z
    depends_on:
      - searxng
      - perplexica-backend
      - perplexica-frontend
    ports:
      - 8443:8443
    networks:
      - perplexica-network
    restart: unless-stopped

networks:
  perplexica-network:

volumes:
  ollama-volume:
  backend-dbstore:
```

And this is my `config.toml`, where I changed my domain names to 'my.domain.name' for sharing it here:

```
[GENERAL]
PORT = 3001 # Port to run the backend server on
SIMILARITY_MEASURE = "cosine" # "cosine" or "dot"

[API_KEYS]
OPENAI = "" # OpenAI API key - sk-1234567890abcdef1234567890abcdef
GROQ = "" # Groq API key - gsk_1234567890abcdef1234567890abcdef
ANTHROPIC = "" # Anthropic API key - sk-ant-1234567890abcdef1234567890abcdef

[API_ENDPOINTS]
SEARXNG = "http://perplexica-searxng-1:8080/" # Internal SearxNG API URL
OLLAMA = "https://my.domain.name/ollama/" # Public Ollama API URL
```

Although I made some more changes than only adding nginx, it's generally working with this configuration files, except the websocket issue. If I e. g. use the 'Writing' mode, instead of the 'All' mode, Ollama generates an answer just fine, since the reaction it seems to be out of any websocket timeout.
