### ISSUE TITLE
Frontend ignores ENV for NEXT_PUBLIC_API_URL/NEXT_PUBLIC_WS_URL

### ISSUE THREAD

**Issue by systemofapwne** [ItzCrazyKns/Perplexica#388]
**Describe the bug**
Setting NEXT_PUBLIC_API_URL and NEXT_PUBLIC_WS_URL via ENV (instead of building the container with Docker ARGs) will cause the frontend to still access the default localhost/127.0.0.1 url.

**To Reproduce**
Use this compose file (no repo checkout etc, just build the stack with this compose file and create a `./data` folder and `./config.toml` and `./perplexica.env` file alongside).
```
services:
  perp-backend:
    image: itzcrazykns1337/perplexica-backend:main
    ports:
      - 3334:3001
    env_file: perplexica.env
    restart: always
    security_opt:
      - no-new-privileges
    volumes:
      - ./data:/home/perplexica/data
      - ./config.toml:/home/perplexica/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  perp-frontend:
    image: itzcrazykns1337/perplexica-frontend:main
    ports:
      - 3333:3000
    env_file: perplexica.env
    restart: always
    security_opt:
      - no-new-privileges
    depends_on:
      - perp-backend
```

And this `perplexica.env` file
```
# Tell frontend where to find the backend
NEXT_PUBLIC_API_URL=http://192.168.0.4:3334/api
NEXT_PUBLIC_WS_URL=ws://192.168.0.4:3334

# Searxng instance
SEARXNG_API_URL=http://web_searx_1:8080
```

**Expected behavior**
The frontend should now use `http://192.168.0.4:3334/api` instead of `http://127.0.0.1:3334/api` but isn't. The env however is present and properly set in the container.

**Screenshots**

![image](https://github.com/user-attachments/assets/6599ac16-fcc5-4fc1-8a5d-fd7c599b194a)
![image](https://github.com/user-attachments/assets/751288cd-c3cf-4afa-be66-1124fc07d3b9)

**Additional context**
I am using a custom compose.yml for my full ai stack, that is in a dedicated git repo. There should be no need to checkout this repo here to deploy perplexica, since the images are are already on dockerhub.
