### ISSUE TITLE
Infinite Loading Issue After Following Docker Installation Tutorial

### ISSUE THREAD

**Issue by kingdomad** [ItzCrazyKns/Perplexica#467]
**Describe the bug**
After following the tutorial steps to start the application using Docker, the page keeps loading indefinitely.

**To Reproduce**

1. Follow the tutorial to start the application using Docker.
2. Access the application’s webpage as instructed in the tutorial.
3. Observe that the page keeps loading without any content.

**Expected behavior**
I expected the page to load normally and display the application content.

**Screenshots**
![image](https://github.com/user-attachments/assets/9ba90782-0632-4af2-b23c-a4d45c66acab)

**Comment by atomicangel** [comment]
I just updated the docker containers on my system and that is when the issue started for me as well. I double checked my configuration (I'm not using a .env file that I can see if that matters.) in the docker-compose.yaml and it looks like it wasn't modified since I last restarted the containers. I then tried `git pull` on the local folder and it made some changes and the issue persists.

I also made sure my ollama instance was up to date as well, to eliminate that as a source of trouble.

**Comment by kingdomad** [comment]
Edit the docker-compose.yaml and change the 127.0.0.1 in the args to the server's IP address:
`
  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:3001/api
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3001
`
This way, it will run successfully.

**Comment by atomicangel** [comment]
I have done that, issue persists. I did that when I had configured it originally so I could access it via a reverse proxy. This is not resolved. I also cannot access it via it's internal address either, and if the settings mentioned matters, then that would explain that but it does not explain why the reverse proxy does not work.On Nov 15, 2024 9:21 PM, kingdomad ***@***.***> wrote:
Edit the docker-compose.yaml and change the 127.0.0.1 in the args to the server's IP address:
perplexica-frontend: build: context: . dockerfile: app.dockerfile args: - NEXT_PUBLIC_API_URL=http://127.0.0.1:3001/api - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3001
This way, it will run successfully.

**Comment by nanhoes** [comment]
same issue

**Comment by ecker00** [comment]
By default it expect API on your local system (http://127.0.0.1:3001/api), you can change this by following networking guide, which requires rebuild.
https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/NETWORKING.md

But if you are lazy and don't want to rebuild, overwrite it on runtime:

```
  perplexica-frontend:
    image: itzcrazykns1337/perplexica-frontend:main
    restart: unless-stopped
    depends_on:
      - perplexica-backend
    ports:
      - 3000:3000
    networks:
      - perplexica-network
    command: >
      sh -c "
      find .next -type f -name '*.js' -exec sed -i 's|ws://127.0.0.1:3001|ws://10.0.5.100:3001|g' {} + &&
      find .next -type f -name '*.js' -exec sed -i 's|http://127.0.0.1:3001/api|http://10.0.5.100:3001/api|g' {} + &&
      yarn start"
 ```
