### ISSUE TITLE
Perplexica behind Caddy

### ISSUE THREAD

**Issue by Scrounger9726** [ItzCrazyKns/Perplexica#497]
Has anyone figured out how to expose Perplexica via caddy reverse proxy?  

All I get is the spinning wheel when the front end loads

Any help would be great

Thanks,

**Comment by Scrounger9726** [comment]
OK I figured it out

**Comment by pazpi** [comment]
Thanks! I tried to replicate this but it took me a while to figure it out but there are two asterisk (`*`) in `header Connection *Upgrade*` which are mandatory otherwise the websocket is broken.

So the full part is:
```
perplexica.[my-domain] {
	@websockets {
		header Connection *Upgrade*
		header Upgrade websocket
	}
	reverse_proxy [your local ip addres]:3000
	reverse_proxy /api* [your local ip addres]:3001
	reverse_proxy @websockets {
		header_up Host [your local ip addres]
		to [your local ip addres]:3001
	}
}
```

**Comment by stanthewizzard** [comment]
Hello

Coudl you help ?

In caddy I change to 

```
perplexica.xxxx.com {
	tls /root/SSL/xxxx.com/fullchain.pem /root/SSL/xxxx.com/xxxx.com.key
	@websockets {
		header Connection *Upgrade*
		header Upgrade websocket
	}
	reverse_proxy docker20service:23000
	reverse_proxy /api* docker20service:23001
	reverse_proxy @websockets {
		header_up Host docker20service
		to docker20service:23001
	}
}
```

In compose perplexica, I changed to:

```
  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://perplexica.xxxx.com/api
        - NEXT_PUBLIC_WS_URL=ws://perplexica.xxxx.com
```

docker compose down --rmi all
docker compose up -d --build

Still having
Failed to connect to the server. Please try again later.

Thanks for help
