### ISSUE TITLE
 NEXT_PUBLIC_(API/WS)_URL settings aren't respected

### ISSUE THREAD

**Issue by kursad-k** [ItzCrazyKns/Perplexica#536]
Hi,

I override these in the docker-compose file because I am running it behind a VPN and the browser clients need to access  the service on other VPN connected devices, however none of those clients can successfully open the page because of network access issue it seems.

I can access and use the app on the computer that is running it under WSL Docker, but other devices on the same VPN network can't fully load the page. The user only sees a loading circle (see the image) The browser console prints the lines below.

```
453-64f6ddb9c5055700.js:1 
 GET http://127.0.0.1:3001/api/models net::ERR_CONNECTION_REFUSED
```

Respective docker compose env variables. These  IPs normally default to `127.0.0.1` in the original docker compose file.

```
perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://VPN-IP-OF-THE-WSL:3001/api
        - NEXT_PUBLIC_WS_URL=ws://VPN-IP-OF-THE-WLS:3001
```

```
http://VPN-IP-OF-THE-WSL:3001/api
{"status":"ok"}
```

![chrome_FHBDUXJpK2](https://github.com/user-attachments/assets/f0017855-18c2-4309-a0d2-4889a73d28ba)
