### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by shelldandy** [ItzCrazyKns/Perplexica#589]
Are there plans of publishing a docker image so its easier to check out without having to clone the project?

Currently its harder to stay up to date having cloned the repo but also making changes to the docker-compose etc, specially for homelab users then its about managing git modules.

I think the config.toml file can probably be swapped or extended with environmental variables as well in here:

https://github.com/ItzCrazyKns/Perplexica/blob/master/src/config.ts#L34-L53

Im happy to help with a PR if needed

**Comment by ItzCrazyKns** [comment]
There are lots of things that needs to be linked for the images to work, I'd love to hear the feedback from the community about this and then let us see what we can do.

**Comment by mayphilc** [comment]
Im also looking for a working image, using docker files is like pushing your car down the highway, sure you are still traveling with your car but is it the correct way to use it? no.  Docker files are ok if its the only docker service you are managing, but it makes adding your service to an existing stack an absolute nightmare and adds completely unnecessarily complicated maintenance

**Comment by ngoc-minh-do** [comment]
Use docker image without `build` step should be standard way

**Comment by ramkrishna2910** [comment]
Having a published docker image would help a lot towards adoption. +1 to this.

**Comment by kpatdev** [comment]
> Having a published docker image would help a lot towards adoption. +1 to this.

It’s already published. Run the compose without build. It works. 

```yaml
services:
    image: itzcrazykns1337/perplexica:main
    …
```

Need to close this, #673 and others.

**Comment by ramkrishna2910** [comment]
This still needs the user to clone the repo. Can we directly get the image from docker hub or using `docker pull`?

**Comment by RepairYourTech** [comment]
> This still needs the user to clone the repo. Can we directly get the image from docker hub or using `docker pull`?

Man the image is available on docker hub just change your image source in compose....ask claude if you get stuck....

**Comment by RepairYourTech** [comment]
> This still needs the user to clone the repo. Can we directly get the image from docker hub or using `docker pull`?


To set Docker Hub as the source for the Perplexica image in your Docker Compose file, you can specify the image directly from Docker Hub. Here's how:

```yaml
version: '3.8'

services:
  perplexica:
    image: itzcrazykns/perplexica:latest
    # or specify a specific version tag like:
    # image: itzcrazykns/perplexica:v1.0.0
    ports:
      - "3001:3001"
    environment:
      # your environment variables here
    volumes:
      # your volume mounts here
```

Key points:

- **Image name**: The official Perplexica image on Docker Hub is `itzcrazykns/perplexica`
- **Tag**: Use `latest` for the most recent version, or specify a specific version tag
- **No build context**: Remove any `build:` directives since you're pulling from Docker Hub instead of building locally

If you were previously building from source, you'll want to remove the `build:` section and replace it with the `image:` directive pointing to Docker Hub.

Make sure to run `docker-compose pull` before `docker-compose up` to ensure you get the latest version from Docker Hub if you're using the `latest` tag.
