### ISSUE TITLE
Ollama not showing as model provider

### ISSUE THREAD

**Issue by Bink-lab** [ItzCrazyKns/Perplexica#648]
I have followed the steps for if ollama fails to show in the readme, but even then i still dont see it in the model provider tab, i have tried removing the docker images etc...

![Image](https://github.com/user-attachments/assets/ce5db44f-93ab-46f9-84df-de5ab1b2d0fe)

![Image](https://github.com/user-attachments/assets/ff689d10-fb53-4656-93ed-55a747d59cc4)

**Comment by Bink-lab** [comment]
I had some personal issues with my coputer, ive fixed the issue now.

**Comment by ItzCrazyKns** [comment]
If you're on Linux you need to use private ip of the machine not the local loopback address.

**Comment by consistentJake** [comment]
I have the same issue. Finally figure it out: the app is running in a docker, but your ollama serve on host (running in http://localhost:11434). My docker has some problem connect to host network. I eventually replace the network mode of the docker into host mode. Here is the `docker-compose.yaml file` after I change to use host netowrk:
```
services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    network_mode: "host"
    restart: unless-stopped

  app:
    image: itzcrazykns1337/perplexica:main
    build:
      context: .
      dockerfile: app.dockerfile
    environment:
      - SEARXNG_API_URL=http://localhost:8080  # communicate via host network
    network_mode: "host"
    volumes:
      - backend-dbstore:/home/perplexica/data
      - uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
    restart: unless-stopped

volumes:
  backend-dbstore:
  uploads:
````
