### ISSUE TITLE
Failed to connect to the server

### ISSUE THREAD

**Issue by zidanereal5** [ItzCrazyKns/Perplexica#656]
**Describe the bug**
Fresh deployment of the version v1.9.3 with Docker method.
Error msg:
Failed to connect to the server. Please try again later.

![Image](https://github.com/user-attachments/assets/c80aca07-03cb-43d7-b57d-c126dd657338)

**To Reproduce**

1. setting of docker-compose.yaml
searxng:
ports:
      - 7002:8080

perplexica-backend:
ports:
      - 7001:3001

perplexica-frontend:
ports:
      - 7000:3000
 
2. setting of  config.toml
[MODELS.OLLAMA]
API_URL = "http://10.2.147.70:11434" # Ollama API URL - http://host.docker.internal:11434

[API_ENDPOINTS]
SEARXNG = "http://10.2.147.70:7002" # SearxNG API URL localhost:32768 10.2.147.70:7002

3. logs of perplexica-frontend 
yarn run v1.22.22


$ next start

   ▲ Next.js 14.1.4

   - Local:        http://localhost:3000

 ✓ Ready in 313ms
5. logs of perplexica-backend
yarn run v1.22.22

$ npm run db:push && node dist/app.js

> perplexica-backend@1.10.0-rc3 db:push

> drizzle-kit push sqlite

drizzle-kit: v0.22.7

drizzle-orm: v0.31.2

No config path provided, using default path

Reading config file '/home/perplexica/drizzle.config.ts'

[⣷] Pulling schema from database...

[✓] Pulling schema from database...

[i] No changes detected

info: WebSocket server started on port 7001

info: Server is running on port 7001

**Comment by zidanereal5** [comment]
ollama api and searxng api works well.

**Comment by ItzCrazyKns** [comment]
Hey please follow this: https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/NETWORKING.md

Where you update your IP make sure it matches the port as well, it shall work.

**Comment by bright-arparwut** [comment]
> Hey please follow this: https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/NETWORKING.md
> 
> Where you update your IP make sure it matches the port as well, it shall work.

Hi, could you pleases give me some example of IP?
is it localhost:3000 is that right?

thank you

**Comment by Krzysi3k** [comment]
I had the same issue, check your `config.toml` file, you should have OpenAI config as follow:
```
[MODELS.OPENAI]
  API_KEY = "sk-xxxxxx..."
```
if you don't have that, add your OpenAI key manually via web ui, it should automatically update your `config.toml`

![Image](https://github.com/user-attachments/assets/f1e9f50f-8ca6-4bf3-ace2-7d2f53259dc9)

**Comment by zidanereal5** [comment]
> Hey please follow this: https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/NETWORKING.md
> 
> Where you update your IP make sure it matches the port as well, it shall work.

I have changed the docker-compose.yaml file.
Have replaced 127.0.0.1 with the server IP:

args:
  - NEXT_PUBLIC_API_URL=http://10.2.147.70:7001/api
  - NEXT_PUBLIC_WS_URL=ws://110.2.147.70:7001


But still not working.

**Comment by zidanereal5** [comment]
> sk-xxxxxx...

Have input the Ollama URL, that should be enough.

[MODELS.OLLAMA]
API_URL = "http://10.2.147.70:11434"

Otherwise I cannot open the web ui for the key setting.

**Comment by skapytek** [comment]
same error for me. Was running the docker compose as written in the turorial without changing any ports or settings. Ive only added my openai api key and renamed the toml.config file.

**Comment by ItzCrazyKns** [comment]
> > Hey please follow this: https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/NETWORKING.md
> > Where you update your IP make sure it matches the port as well, it shall work.
> 
> I have changed the docker-compose.yaml file. Have replaced 127.0.0.1 with the server IP:
> 
> args:
> 
> * NEXT_PUBLIC_API_URL=http://10.2.147.70:7001/api
> * NEXT_PUBLIC_WS_URL=ws://10.2.147.70:7001
> 
> But still not working.

Did you run `docker compose up -d --build`?

**Comment by ItzCrazyKns** [comment]
> same error for me. Was running the docker compose as written in the turorial without changing any ports or settings. Ive only added my openai api key and renamed the toml.config file.

Can you please provide logs from the browser console and the containers?

**Comment by loosac** [comment]
Hi, i got same issues: hardcoded 127.0.0.1:3001 is inside .js files. My workoround:


docker exec -it perplexica-perplexica-frontend-1 /bin/sh


instide contaienr bash (replace yYOURVALIDIP with desired IP):

for i in `grep '127.0.0.1:3001/' -r . |grep -v cache | cut -d ':' -f1 | sort -u`
do
sed -i 's/127.0.0.1:3001/YOURVALIDIP:3001/g' $i
done

exit


docker commit erplexica-perplexica-frontend-1

**Comment by loosac** [comment]
> > same error for me. Was running the docker compose as written in the turorial without changing any ports or settings. Ive only added my openai api key and renamed the toml.config file.
> 
> Can you please provide logs from the browser console and the containers?

Man, problem is inside .js files in web app. It probably everything works fine -when run from same machine, where perplexica is running. But when docker server is another machine and client connects via network -then issues starts to occur.

**Comment by ItzCrazyKns** [comment]
> > > same error for me. Was running the docker compose as written in the turorial without changing any ports or settings. Ive only added my openai api key and renamed the toml.config file.
> > 
> > 
> > Can you please provide logs from the browser console and the containers?
> 
> Man, problem is inside .js files in web app. It probably everything works fine -when run from same machine, where perplexica is running. But when docker server is another machine and client connects via network -then issues starts to occur.

Its not a problem but rather a feature of NextJS. It embeds the public environment variables in the Javascript code generated, your method of changing the IP is correct but its not recommended because in case something wrong happened during the execution the  Javascript bundle might break.

**Comment by loosac** [comment]
> > > > same error for me. Was running the docker compose as written in the turorial without changing any ports or settings. Ive only added my openai api key and renamed the toml.config file.
> > > 
> > > 
> > > Can you please provide logs from the browser console and the containers?
> > 
> > 
> > Man, problem is inside .js files in web app. It probably everything works fine -when run from same machine, where perplexica is running. But when docker server is another machine and client connects via network -then issues starts to occur.
> 
> Its not a problem but rather a feature of NextJS. It embeds the public environment variables in the Javascript code generated, your method of changing the IP is correct but its not recommended because in case something wrong happened during the execution the Javascript bundle might break.

But while building -variables are not modified correctly. 
1st, like in documentation, secion networking - I've changed IP like specified.
but inside .js still we have 127.0.0.1

My example ss not solution, it's workaround -until problem will be solved.

**Comment by ItzCrazyKns** [comment]
> > > > > same error for me. Was running the docker compose as written in the turorial without changing any ports or settings. Ive only added my openai api key and renamed the toml.config file.
> > > > 
> > > > 
> > > > Can you please provide logs from the browser console and the containers?
> > > 
> > > 
> > > Man, problem is inside .js files in web app. It probably everything works fine -when run from same machine, where perplexica is running. But when docker server is another machine and client connects via network -then issues starts to occur.
> > 
> > 
> > Its not a problem but rather a feature of NextJS. It embeds the public environment variables in the Javascript code generated, your method of changing the IP is correct but its not recommended because in case something wrong happened during the execution the Javascript bundle might break.
> 
> But while building -variables are not modified correctly. 1st, like in documentation, secion networking - I've changed IP like specified. but inside .js still we have 127.0.0.1
> 
> My example is not the solution, it's workaround -until problem will be solved. Please, try by yourself: put docker machine inside your network. Install local Ollama. Next, build perplexica, run. Then try to connect from inside your network, using different computer.
> 
> I'm also very excited by using this project.

So the documentation was built after testing. You probably forgot to add the build argument to the docker compose up command. Try executing `docker compose up -d --build` after changing the IP **exactly as mentioned in the documentation**. It worked for most of the people and I have myself tested it.

**Comment by loosac** [comment]
Thanx, will try it in my second lab machine

**Comment by loosac** [comment]
Ok, maybe it whorth to change this line in readme?

![Image](https://github.com/user-attachments/assets/aef9346a-1618-44ba-a672-dc1161a7cf4b)

**Comment by ItzCrazyKns** [comment]
> Ok, maybe it whorth to change this line in readme?
> 
> ![Image](https://github.com/user-attachments/assets/aef9346a-1618-44ba-a672-dc1161a7cf4b)

That is for installing Perplexica and it doesn't need people to build the images themselves. Its clearly mentioned in the networking guide: https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/NETWORKING.md

**Comment by joveli** [comment]
It's a poor design if Modifying the configuration file need to rebuild the container image. It should be redesigned.

**Comment by ceblan** [comment]
This is a nightmare. I made it work behind traefik with authelia in version v0.10.0-rc3, I' reverting to it.

**Comment by ItzCrazyKns** [comment]
> This is a nightmare. I made it work behind traefik with authelia in version v0.10.0-rc3, I' reverting to it.

I've had feedback from multiple users, they were able to run it behind traefik completely fine. I'll ask them to post their configuration here, there were changes made to the compose file and how things work, have you changed your configuration properly?

**Comment by ItzCrazyKns** [comment]
This is what they're using.

```yaml
services:
  reverse-proxy:
    # The official v3 Traefik docker image
    image: traefik:v3.3
    # Enables the web UI and tells Traefik to listen to docker
    command: 
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.docker.localhost`)"
      - "traefik.http.routers.api.service=api@internal"

  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searxng.rule=Host(`searxng.docker.localhost`)"
      - "traefik.http.services.searxng.loadbalancer.server.port=8080"
    restart: unless-stopped

  perplexica:
    image: itzcrazykns1337/perplexica:main
    build:
      context: .
      dockerfile: app.dockerfile
    environment:
      - SEARXNG_API_URL=http://searxng:8080
    networks:
      - default
    volumes:
      - backend-dbstore:/home/perplexica/data
      - uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.perplexica.rule=Host(`perplexica.docker.localhost`)"
      - "traefik.http.services.perplexica.loadbalancer.server.port=3000"
    restart: unless-stopped

volumes:
  backend-dbstore:
  uploads:
```
