### ISSUE TITLE
External SearXNG instance

### ISSUE THREAD

**Issue by FaFre** [ItzCrazyKns/Perplexica#669]
I tried to connect perplexica to an external instance, but this will result in the following error:

`perplexica-backend-1  | error: Unhandled Rejection at: [object Promise], reason: Error: 404 status code (no body)`

(There are no further errors including browser js console)

Docker compose:

```yaml
services:
  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: itzcrazykns1337/perplexica-backend:main
    environment:
      - SEARXNG_API_URL=https://searx.be
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/perplexica/data
      - uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:3001/api
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3001
    image: itzcrazykns1337/perplexica-frontend:main
    depends_on:
      - perplexica-backend
    ports:
      - 3000:3000
    networks:
      - perplexica-network
    restart: unless-stopped

networks:
  perplexica-network:

volumes:
  backend-dbstore:
  uploads:
```

Config:
```toml
[GENERAL]
PORT = 3001
SIMILARITY_MEASURE = "cosine"
KEEP_ALIVE = "5m"

[MODELS.OPENAI]
API_KEY = ""

[MODELS.GROQ]
API_KEY = ""

[MODELS.ANTHROPIC]
API_KEY = ""

[MODELS.GEMINI]
API_KEY = ""

[MODELS.CUSTOM_OPENAI]
API_KEY = "xxx"
API_URL = "https://api.deepinfra.com/v1"
MODEL_NAME = "meta-llama/Llama-3.3-70B-Instruct-Turbo"

[MODELS.OLLAMA]
API_URL = ""

[API_ENDPOINTS]
SEARXNG = "https://searx.be"
```

Also rebuilt everything using
```bash
docker compose down --rmi all
docker compose up -d --build
```
