### ISSUE TITLE
[Feature Request] Simplify Docker Compose (drop requirement to clone repo) - upvote if you agree

### ISSUE THREAD

**Issue by kpatdev** [ItzCrazyKns/Perplexica#673]
## Is your feature request related to a problem? Please describe.

Currently, in order to run Perplexica on Docker you have to clone down the repo and build the containers. This is a step that should be unnecessary as every time the app is updated you have to [reclone](https://github.com/ItzCrazyKns/Perplexica/blob/master/docs/installation/UPDATING.md) the repo and rebuild. While I understand that this is extending prebuilt images, it still shouldn't be required.

> [!NOTE]
> @ItzCrazyKns is currently unifying Perplexica into 1 image. There currently is no ETA on when this will be complete. This is a request to reduce the barrier to continuous deployment on Docker in the meantime.

## Describe the solution you'd like

The docker-compose.yaml file should not require the building/extending of any image. The pre-built images that are already provided should contain everything that is needed for running Perplexica.

There should be no requirement to clone down the repo. Prebuilt images should contain everything that is needed and any customizable variables should be present in either the `.env` or the `config.toml`.

.env:
```env
SEARXNG_API_URL=http://searxng:8080
NEXT_PUBLIC_API_URL=http://127.0.0.1:3001/api
NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3001
```

The config.toml that's already provided shouldn't need to be changed.

docker-compose.yaml:
```yaml
services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-backend:
    image: itzcrazykns1337/perplexica-backend:main
    environment:
      - SEARXNG_API_URL=${SEARXNG_API_URL}
    depends_on:
      - searxng
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/perplexica/data
      - uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-frontend:
    image: itzcrazykns1337/perplexica-frontend:main
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
    depends_on:
      - perplexica-backend
    ports:
      - 3000:3000
    networks:
      - perplexica-network
    restart: unless-stopped

networks:
  perplexica-network:

volumes:
  backend-dbstore:
  uploads:
```

> [!NOTE]
> If you're not running your own SearXNG instance, you'll still need to use the proper files located [here](https://github.com/ItzCrazyKns/Perplexica/tree/master/searxng).

## Additional context

We discussed at length here: #661 @ItzCrazyKns @mayphilc. Per his request, I've created a separate issue to gauge interest in simplification of the docker deployment as a stop-gap prior to the unification he is currently planning.

Related:
#570 
#565 
#581 

There's many issues/discussions that are related to this. This should be addressed to allow for smoother adoption.

---

### If you are interested in this, please upvote/leave a comment on any additional changes you'd want.
