### ISSUE TITLE
Perplexica Installation on Debian 12 LXC with GPU Passthrough - Connection Failure

### ISSUE THREAD

**Issue by GhassanYusuf** [ItzCrazyKns/Perplexica#690]
### Environment
- Debian 12 LXC container on Proxmox
- GPU passthrough configured
- CUDA and NVIDIA driver installed
- Docker and NVIDIA Container Toolkit installed

### Steps Taken
1. Cloned Perplexica repository
2. Configured `config.toml`
3. Created `docker-compose.yaml` (see below)
4. Ran `docker compose up -d`

### Docker Compose Configuration
```yaml
services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - perplexica-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: itzcrazykns1337/perplexica-backend:main
    environment:
      - SEARXNG_API_URL=http://searxng:8080
      - OLLAMA_API_URL=http://ollama:11434
    depends_on:
      ollama:
        condition: service_started
      searxng:
        condition: service_started
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/perplexica/data
      - uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:3001/api
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3001
    image: itzcrazykns1337/perplexica-frontend:main
    depends_on:
      ollama:
        condition: service_started
      perplexica-backend:
        condition: service_started
    ports:
      - 3000:3000
    networks:
      - perplexica-network
    restart: unless-stopped

networks:
  perplexica-network:

volumes:
  backend-dbstore:
  uploads:
  ollama_data:
```

### Current Issue
After deployment, accessing the web interface results in:
1. Initial spinning cursor
2. Error message: "Failed to connect to the server. Please try again later."
3. Unable to access settings or any functionality

### Troubleshooting Performed
- Verified containers are running (`docker ps`)
- Checked container logs (`docker logs `)
- Confirmed SearxNG accessible at http://localhost:4000/

### Questions
1. How to diagnose the connection issue between frontend and backend?
2. Which logs should be examined for the root cause?
3. Are there potential network issues within LXC or Docker?
4. Any missed configuration steps or environment variables?
5. How to verify GPU utilization, especially for Ollama?
6. Any known issues running Perplexica in LXC?
7. Needed adjustments in docker-compose.yaml for inter-service communication?

Thank you for your assistance in resolving this installation and connection issue.
