### ISSUE TITLE
Node module onnxruntime-node throws library errors on startup

### ISSUE THREAD

**Issue by enticedwanderer** [ItzCrazyKns/Perplexica#694]
**Describe the bug**
It seems at least v1.10.0-amd64 image throws errors for `onnxruntime-node` module. Likely native access not being allowed due to lack of missing dynamic shared libraries? Not sure if it's relevant or not. Thought originally it didn't start at all, but it did.

**To Reproduce**

Pull the v1.10.0-amd64 image on any linux machine and try to start it.

**Expected behavior**
Should start without issues.

**Screenshots**
```console
root@dockerino:/docker/config/perplexica# dclogs -f -n500
perplexica  |    ▲ Next.js 15.2.2
perplexica  |    - Local:        http://6f1aec724fdc:3000
perplexica  |    - Network:      http://6f1aec724fdc:3000
perplexica  |
perplexica  |  ✓ Starting...
perplexica  |  ✓ Ready in 114ms
perplexica  | [Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /home/perplexica/node_modules/onnxruntime-node/bin/napi-v3/linux/x64//libonnxruntime.so.1.14.0)] {
perplexica  |   code: 'ERR_DLOPEN_FAILED'
perplexica  | }
perplexica  |  ⨯ unhandledRejection:  [Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /home/perplexica/node_modules/onnxruntime-node/bin/napi-v3/linux/x64//libonnxruntime.so.1.14.0)] {
perplexica  |   code: 'ERR_DLOPEN_FAILED'
perplexica  | }
```

**Additional context**
In case it matters my docker-compose:

```yaml
root@dockerino:/docker/config/perplexica# cat docker-compose.yaml
services:
  perplexica:
    image: itzcrazykns1337/perplexica:v1.10.0-amd64
    container_name: perplexica
    environment:
      - SEARXNG_API_URL=https://searx.home.lan
    networks:
      - traefik-network
    volumes:
      - backend-dbstore:/home/perplexica/data
      - uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
    labels:
      - traefik.enable=true
      - traefik.http.routers.perplexica.rule=Host(`perplexica.home.lan`)
      - traefik.http.routers.perplexica.entrypoints=web,web-secure
      - traefik.http.routers.perplexica.middlewares=secured@file
      - traefik.http.services.perplexica.loadbalancer.server.port=3000
      - wud.watch=false
    restart: always
networks:
  traefik-network:
    external: true
volumes:
  backend-dbstore:
  uploads:
```
