### ISSUE TITLE
Integration of Modern LLM-Optimized Search Engines like Tavily and others

### ISSUE THREAD

**Issue by goodmaney** [ItzCrazyKns/Perplexica#709]
It's great to see the recent updates you've made to the Perplexica.

Given the growing popularity of search engines specifically designed for LLM applications, I propose enhancing Perplexica by:

Integrating modern LLM-optimized search APIs such as:

# Tavily
# Exa
# Firecrawl
# jina-ai
Significantly expanding our reference source pool to:

Improve result comprehensiveness
Enhance answer accuracy
Support better citation capabilities
This upgrade would align our system with current industry standards where many LLM clients are already adopting these specialized search solutions.

**Comment by arsaboo** [comment]
@ItzCrazyKns search seems to be the bottleneck right now (unfortunately, SearXNG is not very reliable). It will be great to have some good search providers.

**Comment by singleparadox** [comment]
Maybe crawl4ai should also be considered because it is open source and free.

https://github.com/unclecode/crawl4ai

**Comment by elvenking** [comment]
Please do Exa AI Websets integration. That would be awesome :)

**Comment by kmataru** [comment]
For anyone interested in setting up Tavily as a search engine, you can add the following to the `settings.yml`:

```yaml
engines:
  - name: tavily
    engine: json_engine
    shortcut: tv
    categories:
      - general
    disabled: false
    timeout: 15.0

    search_url: https://api.tavily.com/search
    method: POST

    headers:
      Content-Type: application/json
      Authorization: "Bearer {your tavily key goes here}"

    request_body: >-
      {{
        "query": "{query}",
        "search_depth": "basic",
        "max_results": 10,
        "include_answer": false,
        "include_raw_content": false,
        "include_images": false
      }}

    results_query: results
    url_query: url
    title_query: title
    content_query: content
```

`docker-compose.yml`:
```yaml
services:
  vane:
    image: itzcrazykns1337/vane:latest
    restart: unless-stopped
    ports:
      - "2999:3000"
      - "8888:8080"
    volumes:
      - vane-data:/home/vane/data
      - ./settings.yml:/etc/searxng/settings.yml:ro

volumes:
  vane-data:  
```
